### ISSUE TITLE
Create Matching interface

### ISSUE THREAD

**Issue by ycewe** [nus-mtp/steps-networking-module#143]
Criteria:
1. Create an dropdown field that accepts the pre-defined keywords e.g. `internship`, `partnership`, etc
2. Create a logic component that processes the input and outputs result(s) with the matching keywords
3. Logic component should have open APIs that can be called from any other components

**Comment by Muhammad-Adam** [comment]
Can you provide me with some other predefined keywords? And am I correct to say given any project, they will belong to AT LEAST ONE of the predefined keywords?
