### ISSUE TITLE
Search Bugs

### ISSUE THREAD

**Issue by JeanKoh** [nus-mtp/steps-networking-module#252]
Search for '7th', it will show invalid, but still shows the correct exhibitions.

Search for '10th' - invalid search after using valid search, show exhibition will show old search result for exhibition.

**Comment by Sean-Tay** [comment]
Actually is the contains search desirable?
Right now we have exact search for everything else, but only for searchExhibitionsByEvent do we have the contains search behaviour.

**Comment by ycewe** [comment]
@Sean-Tay I actually have an auto complete i.e. I get all events first then use .contains() on client side to output exact results. If you are using .contains() for one, use for all others, or don't use. Otherwise it will be incoherent.

**Comment by Sean-Tay** [comment]
Then let's keep it on the client side. I'll remove the related functionality from the Attendances routes as well.

**Comment by Sean-Tay** [comment]
Resolved with #257
