### ISSUE TITLE
Profile Rendering Bugs

### ISSUE THREAD

**Issue by JeanKoh** [nus-mtp/steps-networking-module#262]
Scenario 1:
connect to localhost, account already logged in from last session
press profile, it works.
log out. log into another account.
press profile, it shows the profile of the old account.

Scenario 2:
connect to localhost, reach login page.
log in.
press profile, does not work
warning message: browser.js:49 Warning: [react-router] Location "/profile/" did not match any routes

**Comment by Muhammad-Adam** [comment]
@JeanKoh Can you go to develop, pull the lastest commit and see whether the bug still persist?

**Comment by JeanKoh** [comment]
@Muhammad-Adam yes still happening.

**Comment by Muhammad-Adam** [comment]
@JeanKoh Both scenario?

**Comment by JeanKoh** [comment]
@Muhammad-Adam  yes.

**Comment by JeanKoh** [comment]
![image](https://cloud.githubusercontent.com/assets/12741736/24603168/52914386-1892-11e7-9e4d-3a28d275f28e.png)

**Comment by Muhammad-Adam** [comment]
Hmm..this is routing problem. Im not sure how to handle this. @ycewe, how to solve this?
