### ISSUE TITLE
Home Page - Mobile view Bug

### ISSUE THREAD

**Issue by JeanKoh** [nus-mtp/steps-networking-module#300]
Collapsible reached max length, unable to see "attending" options.
![17806754_10211369436086003_398440600_n](https://cloud.githubusercontent.com/assets/12741736/24671582/90584e90-19a4-11e7-9a5e-b133bfd9bdec.png)

**Comment by JeanKoh** [comment]
![overflow](https://cloud.githubusercontent.com/assets/12741736/24695932/52ed0688-1a1a-11e7-9d85-3c36a720cafb.png)
Also, the matching will be overflowed.

**Comment by Muhammad-Adam** [comment]
I know. Its fixed in my branch alr
