### ISSUE TITLE
Home Page Event Bugs

### ISSUE THREAD

**Issue by JeanKoh** [nus-mtp/steps-networking-module#301]
![pic](https://cloud.githubusercontent.com/assets/12741736/24672329/e4f757c8-19a6-11e7-8cc9-caab631713cd.png)
1) printing error message on image overlay
2) I don't think you should put the image name on the overlay, doesn't look professional.
3) You can open collapsible when clicking on the images for the last event (the one without any image). But it doesn't work for the first three which contains images.

**Comment by ycewe** [comment]
@JeanKoh 
1. I can't reproduce that error. Can you show the step to reproduce this? Or is it a caching issue?
2. Overlay name is done with HTML embed
3. You can open collapsible because there is no HTML embed in the last one

**Comment by JeanKoh** [comment]
1. Seems to be gone now. So it's fine~
