### ISSUE TITLE
Part of Sign Up/ Login Page is being covered by nav bar

### ISSUE THREAD

**Issue by Muhammad-Adam** [nus-mtp/steps-networking-module#334]

**Comment by ycewe** [comment]
@adam what talking you?
![capture5](https://cloud.githubusercontent.com/assets/6072229/24766960/eb5eea6a-1b2f-11e7-9730-5025437f5afd.PNG)

**Comment by Muhammad-Adam** [comment]
Eh... I cannot reproduce the error now. Lol
