### ISSUE TITLE
Create tracks to filter exhibitions

### ISSUE THREAD

**Issue by ycewe** [nus-mtp/steps-networking-module#339]
Motivation:
Prof Anand wants a filter like http://isteps.comp.nus.edu.sg/event/10th-steps/modules instead of show all

Criteria:
1. Create a filter that is toggleable and changes view depending on the tracks
2. Tracks should be open ended and not tied to modules by STePs only. Think long term.

**Comment by Muhammad-Adam** [comment]
How to track. I still dont get it. You mean like sidebar ah?

**Comment by ycewe** [comment]
Yes. Side or top up to you. Its not track. Its tracks. Like cd player. You listen music got Track 1, Track 2.
