### ISSUE TITLE
Specify Exhibition specific participation reasons in User Profile

### ISSUE THREAD

**Issue by Vylantze** [nus-mtp/steps-networking-module#46]
Tied to #47 

Criteria:
1. In user profile, there is a dropdown for each exhibition they have
2. Each dropdown has pre-defined an pre-defiined option
3. Users are able to specify the reason for each exhibition and update their reason
4. Reasons are saved in the database

**Comment by Muhammad-Adam** [comment]
Same as #48 
Update and specify are synonyms in this case.
